import os
import math
import csv

def generate_gcode_header():
    return """; FLAVOR:RepRap
; MINX:10
; MINY:10
; MINZ:0
; MAXX:50
; MAXY:50
; MAXZ:20
; Generated by Medical AI Zirconia Optimizer (Z.ai)
M104 S210 ; Set nozzle temp
M140 S60  ; Set bed temp
G28 ; Home all axes
G1 Z5 F5000 ; Lift nozzle
M109 S210 ; Wait for nozzle temp
G92 E0 ; Reset extruder
G1 F200 E3 ; Prime extruder
G92 E0
"""

def generate_gcode_footer():
    return """M104 S0 ; Turn off extruder
M140 S0 ; Turn off bed
G28 X0 Y0 ; Home X/Y
M84 ; Disable motors
"""

def load_patient_nodes():
    import h5py
    nodes = []
    filepath = os.path.join(os.path.dirname(__file__), "..", "Stage4_Robotics", "patient_data_v73.mat")
    if os.path.exists(filepath):
        with h5py.File(filepath, 'r') as f:
            nodes_data = f['nodes'][()]
            # nodes_data may be transposed depending on how MATLAB v7.3 handles it, but since we created it in Python it is (N, 3)
            for row in nodes_data:
                nodes.append((float(row[0]), float(row[1]), float(row[2])))
    else:
        print(f"Warning: {filepath} not found. Using fallback geometry.")
        # Fallback procedural geometry if file is missing (to prevent crash, but warn loudly)
        for z in range(0, 20, 2):
            for angle in range(0, 360, 20):
                r = 15
                x = 30 + r * math.cos(math.radians(angle))
                y = 30 + r * math.sin(math.radians(angle))
                nodes.append((x, y, z))
    return nodes

def generate_anatomical_pre_surgery_gcode(filepath, nodes):
    # Represents a 3D model of the patient's jaw and defect geometry (Stage 1 output)
    gcode = generate_gcode_header()
    gcode += "; Pre-Surgery Anatomical Planning Model (Jawbone & Defect) from Real Patient Data\n"
    
    e_val = 0.0
    
    # Sort nodes by Z to slice into layers
    nodes_sorted = sorted(nodes, key=lambda n: n[2])
    current_z = -1
    
    for (x, y, z) in nodes_sorted:
        # Scale and shift coordinates to fit printer bed
        print_x = 25 + x * 2
        print_y = 25 + y * 2
        print_z = abs(z)
        
        if abs(print_z - current_z) > 0.1:
            current_z = print_z
            gcode += f"G1 Z{current_z:.2f} F1200\n"
            
        e_val += 0.02
        gcode += f"G1 X{print_x:.2f} Y{print_y:.2f} E{e_val:.3f} F1500\n"

    gcode += generate_gcode_footer()
    with open(filepath, "w") as f:
        f.write(gcode)

if __name__ == "__main__":
    out_dir = os.path.dirname(os.path.abspath(__file__))
    os.makedirs(out_dir, exist_ok=True)
    
    nodes = load_patient_nodes()
    generate_anatomical_pre_surgery_gcode(os.path.join(out_dir, "anatomical_pre_surgery_model.gcode"), nodes)
    
    print(f"Successfully generated patient-specific G-Code 3D model in {out_dir}")
